### PR TITLE
Fix LaTex rendering and max nodes warning

### LINKED ISSUE #24982: Crash when opening Threads with latex formula (iOS)
Opening "Threads" from the sidebar leads to a crash:
```

2023/10/13 11:32:25:202 WARNING Handling Javascript error Invariant Violation: View config getter callback for component `span` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in span
    in LatexInline
    in RemoveMarkdown
    in RCTText
    in render
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in TouchableHighlight
    in Unknown
    in Thread
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in VirtualizedListCellContextProvider
    in CellRenderer
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in ScrollView
    in VirtualizedListContextProvider
    in VirtualizedList
    in FlatList
    in ThreadsList
    in ConcreteWithObservablesComponent
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in RNCSafeAreaView
    in Unknown
    in GlobalThreads
    in ConcreteWithObservablesComponent
    in Unknown
    in ThemeProvider
    in ConcreteWithObservablesComponent
    in ServerUrlProvider
    in IntlProvider
    in UserLocaleProvider
    in ConcreteWithObservablesComponent
    in DatabaseProvider
    in ServerDatabaseComponent
    in Provider
    in EmmProvider
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in SafeAreaInsets
    in RCTView
    in Unknown
    in GestureHandlerRootView
    in gestureHoc
    in WrappedComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes 0
2023/10/13 11:32:25:202 ERROR Invariant Violation: View config getter callback for component `span` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in span
    in LatexInline
    in RemoveMarkdown
    in RCTText
    in render
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in TouchableHighlight
    in Unknown
    in Thread
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in VirtualizedListCellContextProvider
    in CellRenderer
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in ScrollView
    in VirtualizedListContextProvider
    in VirtualizedList
    in FlatList
    in ThreadsList
    in ConcreteWithObservablesComponent
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in RNCSafeAreaView
    in Unknown
    in GlobalThreads
    in ConcreteWithObservablesComponent
    in Unknown
    in ThemeProvider
    in ConcreteWithObservablesComponent
    in ServerUrlProvider
    in IntlProvider
    in UserLocaleProvider
    in ConcreteWithObservablesComponent
    in DatabaseProvider
    in ServerDatabaseComponent
    in Provider
    in EmmProvider
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in SafeAreaInsets
    in RCTView
    in Unknown
    in GestureHandlerRootView
    in gestureHoc
    in WrappedComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes
2023/10/13 11:32:25:203 WARNING Handling Javascript error Invariant Violation: View config getter callback for component `span` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in span
    in LatexInline
    in RemoveMarkdown
    in RCTText
    in render
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in TouchableHighlight
    in Unknown
    in Thread
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in VirtualizedListCellContextProvider
    in CellRenderer
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in ScrollView
    in VirtualizedListContextProvider
    in VirtualizedList
    in FlatList
    in ThreadsList
    in ConcreteWithObservablesComponent
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in RNCSafeAreaView
    in Unknown
    in GlobalThreads
    in ConcreteWithObservablesComponent
    in Unknown
    in ThemeProvider
    in ConcreteWithObservablesComponent
    in ServerUrlProvider
    in IntlProvider
    in UserLocaleProvider
    in ConcreteWithObservablesComponent
    in DatabaseProvider
    in ServerDatabaseComponent
    in Provider
    in EmmProvider
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in SafeAreaInsets
    in RCTView
    in Unknown
    in GestureHandlerRootView
    in gestureHoc
    in WrappedComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes 0
2023/10/13 11:32:25:203 ERROR Invariant Violation: View config getter callback for component `span` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in span
    in LatexInline
    in RemoveMarkdown
    in RCTText
    in render
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in TouchableHighlight
    in Unknown
    in Thread
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in VirtualizedListCellContextProvider
    in CellRenderer
    in RCTScrollContentView
    in RCTScrollView
    in ScrollView
    in ScrollView
    in VirtualizedListContextProvider
    in VirtualizedList
    in FlatList
    in ThreadsList
    in ConcreteWithObservablesComponent
    in ConcreteWithObservablesComponent
    in Unknown
    in RCTView
    in Unknown
    in RNCSafeAreaView
    in Unknown
    in GlobalThreads
    in ConcreteWithObservablesComponent
    in Unknown
    in ThemeProvider
    in ConcreteWithObservablesComponent
    in ServerUrlProvider
    in IntlProvider
    in UserLocaleProvider
    in ConcreteWithObservablesComponent
    in DatabaseProvider
    in ServerDatabaseComponent
    in Provider
    in EmmProvider
    in RNCSafeAreaProvider
    in SafeAreaProvider
    in SafeAreaInsets
    in RCTView
    in Unknown
    in GestureHandlerRootView
    in gestureHoc
    in WrappedComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes
2023/10/13 11:32:25:206 WARNING Handling Javascript error {
    componentStack = "\n    in span\n    in LatexInline\n    in RemoveMarkdown\n    in RCTText\n    in render\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in TouchableHighlight\n    in Unknown\n    in Thread\n    in ConcreteWithObservablesComponent\n    in Unknown\n    in RCTView\n    in Unknown\n    in VirtualizedListCellContextProvider\n    in CellRenderer\n    in RCTScrollContentView\n    in RCTScrollView\n    in ScrollView\n    in ScrollView\n    in VirtualizedListContextProvider\n    in VirtualizedList\n    in FlatList\n    in ThreadsList\n    in ConcreteWithObservablesComponent\n    in ConcreteWithObservablesComponent\n    in Unknown\n    in RCTView\n    in Unknown\n    in RNCSafeAreaView\n    in Unknown\n    in GlobalThreads\n    in ConcreteWithObservablesComponent\n    in Unknown\n    in ThemeProvider\n    in ConcreteWithObservablesComponent\n    in ServerUrlProvider\n    in IntlProvider\n    in UserLocaleProvider\n    in ConcreteWithObservablesComponent\n    in DatabaseProvider\n    in ServerDatabaseComponent\n    in Provider\n    in EmmProvider\n    in RNCSafeAreaProvider\n    in SafeAreaProvider\n    in SafeAreaInsets\n    in RCTView\n    in Unknown\n    in GestureHandlerRootView\n    in gestureHoc\n    in WrappedComponent\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in AppContainer";
    framesToPop = 1;
    isComponentError = 1;
    jsEngine = hermes;
    name = "Invariant Violation";
} 1
```

Application info:
```
Current User Id: c1kc6qfwm3dk8jqbnuyo1a5agy
Current Team Id: ihhmpw5r37robps4hzh4wzaojo
Server Version: 8.1.1 (Build 8.1.1)
App Version: 2.8.2 (Build 488)
App Platform: ios
Device Model: iPhone14,6
```

### PR DESCRIPTION
**Pull request by jannikbertram**
#### Summary
The rendering of LaTex in messages is currently broken. 
In channels, LaTex is simply not showing up. In "Threads", the app crashes when a thread contains LaTex. 

The warning for messages with too many nodes is also not showing up.

The error is caused by false naming of type aliases. Due to the code design, the keys of type aliases have to be lowercased. 

#### Screenshots
|  before  |  after  |
|----|----|
| Screenshot 2023-10-24 at 22 58 50 | Screenshot 2023-10-24 at 22 59 50 
| Screenshot 2023-10-24 at 22 58 25 | Screenshot 2023-10-24 at 22 58 35 
| Screenshot 2023-10-24 at 22 54 41 | Screenshot 2023-10-24 at 22 54 59 |

#### Ticket Link
Closes https://github.com/mattermost/mattermost/issues/24982

### CODE REVIEW

File: src/commonmark-react-renderer.js [hunk 1]
```diff
@@ -18,8 +18,8 @@ var typeAliases = {
     editedindicator: 'edited_indicator',
     tableRow: 'table_row',
     tableCell: 'table_cell',
-    latexInline: 'latex_inline',
-    maxNodesWarning: 'max_nodes_warning'
+    latexinline: 'latex_inline',
+    maxnodeswarning: 'max_nodes_warning'
```
Comment (jannikbertram) [inline src/commonmark-react-renderer.js:22]: Type aliases are accessed by this function which expects the keys to be lowercased
```
function normalizeTypeName(typeName) {
    var norm = typeName.toLowerCase();
    var type = typeAliases[norm] || norm;
    return typeof defaultRenderers[type] !== 'undefined' ? type : typeName;
}
```

Comment (jannikbertram) [reply src/commonmark-react-renderer.js:23]: A potentially better fix would be to allow type aliases to be camel-cased. I'm hesitant to do that because we'd have to make sure that all usages in mattermost-mobile match the keys exactly, which might be prone to errors

**Review by enahum — APPROVED** [review]

**Comment by enahum** [comment]
@hmhealey can you double check?

**Comment by jannikbertram** [comment]
I added some screenshots as well to show the effect of the changes

**Review by hmhealey — APPROVED** [review]
Great catch! I'm not sure how I missed this before, but I guess I must've only tested tables, latex, and that warning message in the post list and not the thread list. I'm surprised it's taken so long for someone to encounter that error though

**Comment by hmhealey** [comment]
@jannikbertram Thanks for this fix. Would you also be open to submitting a PR to update the mobile app to use the new version of this library? If not, no worries

**Comment by jannikbertram** [comment]
No worries @hmhealey, yeah I'd like to create a PR to update the library version, too. Will do it tomorrow
